import { Barcode, Zap, ShieldCheck, ShoppingCart, Crown } from "lucide-react";

export const BARCODE_PACKAGES = [
  {
    id: "starter",
    name: "Starter",
    count: 1,
    price: 1499,
    description: "Perfect for a single product launch",
    features: ["1 Unique Barcode", "Lifetime Validity", "PDF Certificate", "Instant Delivery"],
    color: "from-blue-500/20 to-blue-600/10",
    border: "border-blue-500/30 hover:border-blue-400/60",
    shopColor: "from-blue-500 to-blue-700",
    iconName: "Barcode",
  },
  {
    id: "growth",
    name: "Growth",
    count: 5,
    price: 5999,
    description: "Ideal for small product ranges",
    features: ["5 Unique Barcodes", "Lifetime Validity", "PDF Certificate", "Instant Delivery", "Priority Support"],
    color: "from-indigo-500/20 to-indigo-600/10",
    border: "border-indigo-500/30 hover:border-indigo-400/60",
    shopColor: "from-indigo-500 to-indigo-700",
    iconName: "Zap",
  },
  {
    id: "business",
    name: "Business",
    count: 10,
    price: 7999,
    description: "Most popular for growing brands",
    features: ["10 Unique Barcodes", "Lifetime Validity", "PDF Certificate", "Instant Delivery", "Priority Support", "High-res Images"],
    color: "from-orange-500/20 to-orange-600/10",
    border: "border-orange-500/40 hover:border-orange-400/70",
    shopColor: "from-orange-500 to-orange-700",
    popular: true,
    iconName: "ShieldCheck",
  },
  {
    id: "professional",
    name: "Professional",
    count: 20,
    price: 11999,
    description: "Scale your business with ease",
    features: ["20 Unique Barcodes", "Lifetime Validity", "PDF Certificate", "Instant Delivery", "Dedicated Account Manager", "Custom Branding"],
    color: "from-purple-500/20 to-purple-600/10",
    border: "border-purple-500/30 hover:border-purple-400/60",
    shopColor: "from-purple-500 to-purple-700",
    iconName: "ShoppingCart",
  },
  {
    id: "enterprise-lite",
    name: "Enterprise Lite",
    count: 50,
    price: 19999,
    description: "For large inventory needs",
    features: ["50 Unique Barcodes", "Lifetime Validity", "PDF Certificate", "Instant Delivery", "Dedicated Account Manager", "Wholesale Pricing"],
    color: "from-teal-500/20 to-teal-600/10",
    border: "border-teal-500/30 hover:border-teal-400/60",
    shopColor: "from-teal-500 to-teal-700",
    iconName: "Barcode",
  },
  {
    id: "enterprise-pro",
    name: "Enterprise Pro",
    count: 100,
    price: 34999,
    description: "Comprehensive retail solution",
    features: ["100 Unique Barcodes", "Lifetime Validity", "PDF Certificate", "Instant Delivery", "24/7 Priority Support", "Global Retail Readiness"],
    color: "from-slate-700/20 to-slate-900/10",
    border: "border-slate-500/30 hover:border-slate-400/60",
    shopColor: "from-slate-700 to-slate-900",
    iconName: "Crown",
  },
];

export const SPECIAL_PACKAGE = {
  id: "unlimited",
  name: "Special Unlimited Package",
  count: "Unlimited",
  price: 69999,
  period: "/ Year",
  description: "The ultimate solution for high-volume manufacturers and retailers",
  features: [
    "Unlimited Barcode Generation",
    "1 Year Full Access",
    "Premium Support Desk",
    "Wholesale Portal Access",
    "Custom Reporting Tools",
    "Compliance Assistance",
    "Identity Verification Service"
  ],
  color: "from-orange-400/20 via-orange-500/15 to-orange-600/10",
  border: "border-orange-400/50 hover:border-orange-400/80",
  shopColor: "from-orange-400 via-orange-500 to-orange-600",
};
